"use client";

import Image from "next/image";
import Link from "next/link";
import { ArrowLeft } from "lucide-react";

export default function QRCodeDetailsPage() {
  return (
    <main className="min-h-screen bg-[#0B0B0B] text-white p-8">

      {/* Header */}

      <div className="flex justify-between items-center mb-10">

        <div>

          <h1 className="text-4xl font-bold text-yellow-500">
            QR Code Details
          </h1>

          <p className="text-gray-400 mt-2">
            View QR Code information
          </p>

        </div>

        <Link
          href="/products/qrcode"
          className="flex items-center gap-2 border border-yellow-500 text-yellow-500 px-5 py-3 rounded-xl hover:bg-yellow-500 hover:text-black transition"
        >
          <ArrowLeft size={18} />
          Back
        </Link>

      </div>

      {/* Card */}

      <div className="bg-[#141414] border border-yellow-500/20 rounded-2xl p-8 grid lg:grid-cols-2 gap-10">

        {/* QR Code */}

        <div className="bg-white rounded-xl flex justify-center items-center p-8">

          <Image
            src="/qrcode/qrcode1.png"
            alt="QR Code"
            width={250}
            height={250}
            className="object-contain"
          />

        </div>

        {/* Details */}

        <div className="space-y-5">

          <h2 className="text-3xl font-bold text-yellow-500">
            Gold Ring
          </h2>

          <p>
            <span className="text-gray-400">SKU :</span> GLD001
          </p>

          <p>
            <span className="text-gray-400">QR Value :</span>
            https://luxurygolderp.com/product/GLD001
          </p>

          <p>
            <span className="text-gray-400">QR Type :</span>
            Product URL
          </p>

          <p>
            <span className="text-gray-400">Generated By :</span>
            Admin
          </p>

          <p>
            <span className="text-gray-400">Created On :</span>
            24 July 2026
          </p>

          <div>

            <h3 className="text-xl font-semibold text-yellow-500 mb-3">
              Description
            </h3>

            <p className="text-gray-400 leading-8">
              This QR Code allows quick access to the product details,
              pricing, inventory status, and other information within
              the Luxury Gold ERP System.
            </p>

          </div>

          <button
            className="mt-6 bg-yellow-500 hover:bg-yellow-400 text-black font-semibold px-8 py-3 rounded-xl transition"
          >
            Download QR Code
          </button>

        </div>

      </div>

    </main>
  );
}