"use client";

import { useState, useEffect } from "react";

export default function AIInsightsPage() {
  const [data, setData] = useState({
    todaysSales: 245000,
    bestSellingProduct: "22K Gold Ring",
    lowStockItems: 12,
    pendingRepairs: 8
  });
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    async function fetchInsights() {
      try {
        const res = await fetch("/api/ai/insights");
        if (res.ok) {
          const json = await res.json();
          setData({
            todaysSales: json.todaysSales || 0,
            bestSellingProduct: json.bestSellingProduct || "N/A",
            lowStockItems: json.lowStockItems || 0,
            pendingRepairs: json.pendingRepairs || 0
          });
        }
      } catch (err) {
        console.error(err);
      } finally {
        setLoading(false);
      }
    }
    fetchInsights();
  }, []);

  return (
    <main className="min-h-screen bg-background-primary text-text-primary p-8">
      <h1 className="text-4xl font-bold text-accent-gold">
        AI Insights
      </h1>

      <p className="text-text-secondary mt-3">
        Business insights generated by the AI Assistant.
      </p>

      {loading ? (
        <div className="mt-12 text-center text-text-secondary">Loading your AI insights...</div>
      ) : (
        <div className="grid grid-cols-1 md:grid-cols-2 gap-6 mt-8">
          <div className="bg-background-secondary border border-border-theme rounded-2xl p-6 transition hover:border-accent-gold/50 hover:shadow-[0_0_15px_rgba(212,175,55,0.05)]">
            <h2 className="text-accent-gold text-xl font-semibold">
              Today's Sales
            </h2>
            <p className="text-3xl font-bold mt-3">
              ₹{data.todaysSales.toLocaleString("en-IN")}
            </p>
          </div>

          <div className="bg-background-secondary border border-border-theme rounded-2xl p-6 transition hover:border-accent-gold/50 hover:shadow-[0_0_15px_rgba(212,175,55,0.05)]">
            <h2 className="text-accent-gold text-xl font-semibold">
              Best Selling Product
            </h2>
            <p className="text-3xl font-bold mt-3">
              {data.bestSellingProduct}
            </p>
          </div>

          <div className="bg-background-secondary border border-border-theme rounded-2xl p-6 transition hover:border-accent-gold/50 hover:shadow-[0_0_15px_rgba(212,175,55,0.05)]">
            <h2 className="text-accent-gold text-xl font-semibold">
              Low Stock Items
            </h2>
            <p className="text-3xl font-bold mt-3">
              {data.lowStockItems}
            </p>
          </div>

          <div className="bg-background-secondary border border-border-theme rounded-2xl p-6 transition hover:border-accent-gold/50 hover:shadow-[0_0_15px_rgba(212,175,55,0.05)]">
            <h2 className="text-accent-gold text-xl font-semibold">
              Pending Repairs
            </h2>
            <p className="text-3xl font-bold mt-3">
              {data.pendingRepairs}
            </p>
          </div>
        </div>
      )}
    </main>
  );
}