export default function AIInsightsPage() {
  return (
    <main className="min-h-screen bg-[#0B0B0B] text-white p-8">
      <h1 className="text-4xl font-bold text-yellow-500">
        AI Insights
      </h1>

      <p className="text-gray-400 mt-3">
        Business insights generated by the AI Assistant.
      </p>

      <div className="grid grid-cols-1 md:grid-cols-2 gap-6 mt-8">

        <div className="bg-[#141414] border border-yellow-500/20 rounded-2xl p-6">
          <h2 className="text-yellow-500 text-xl font-semibold">
            Today's Sales
          </h2>

          <p className="text-3xl font-bold mt-3">
            ₹2,45,000
          </p>
        </div>

        <div className="bg-[#141414] border border-yellow-500/20 rounded-2xl p-6">
          <h2 className="text-yellow-500 text-xl font-semibold">
            Best Selling Product
          </h2>

          <p className="text-3xl font-bold mt-3">
            22K Gold Ring
          </p>
        </div>

        <div className="bg-[#141414] border border-yellow-500/20 rounded-2xl p-6">
          <h2 className="text-yellow-500 text-xl font-semibold">
            Low Stock Items
          </h2>

          <p className="text-3xl font-bold mt-3">
            12
          </p>
        </div>

        <div className="bg-[#141414] border border-yellow-500/20 rounded-2xl p-6">
          <h2 className="text-yellow-500 text-xl font-semibold">
            Pending Repairs
          </h2>

          <p className="text-3xl font-bold mt-3">
            8
          </p>
        </div>

      </div>
    </main>
  );
}