import {
  Download,
  FileText,
  Calendar,
  Users,
  Wallet,
  TrendingUp,
} from "lucide-react";

const reports = [
  {
    title: "Attendance Report",
    description: "Monthly employee attendance summary",
    icon: Calendar,
    color: "text-green-400",
  },
  {
    title: "Payroll Report",
    description: "Salary & payroll transaction report",
    icon: Wallet,
    color: "text-yellow-400",
  },
  {
    title: "Employee Report",
    description: "Complete employee information",
    icon: Users,
    color: "text-blue-400",
  },
  {
    title: "Performance Report",
    description: "Performance evaluation report",
    icon: TrendingUp,
    color: "text-purple-400",
  },
];

export default function ReportsPage() {
  return (
    <div className="p-8 space-y-8">

      {/* Header */}

      <div className="flex items-center justify-between">

        <div>
          <h1 className="text-3xl font-bold text-white">
            HR Reports
          </h1>

          <p className="text-gray-400 mt-2">
            Generate and download HR & Payroll reports.
          </p>
        </div>

        <button className="flex items-center gap-2 bg-yellow-500 hover:bg-yellow-400 text-black px-5 py-2 rounded-lg font-semibold">
          <Download size={18} />
          Export All
        </button>

      </div>

      {/* Report Cards */}

      <div className="grid grid-cols-1 md:grid-cols-2 gap-6">

        {reports.map((report) => {
          const Icon = report.icon;

          return (
            <div
              key={report.title}
              className="bg-[#111111] border border-zinc-800 rounded-2xl p-6 hover:border-yellow-500 transition"
            >
              <div className="flex items-center justify-between">

                <div>

                  <div className="w-14 h-14 rounded-xl bg-zinc-900 flex items-center justify-center">
                    <Icon className={report.color} size={28} />
                  </div>

                  <h2 className="text-xl font-semibold text-white mt-5">
                    {report.title}
                  </h2>

                  <p className="text-gray-400 mt-2">
                    {report.description}
                  </p>

                </div>

                <button className="bg-yellow-500 hover:bg-yellow-400 text-black px-4 py-2 rounded-lg font-medium flex items-center gap-2">
                  <Download size={16} />
                  Download
                </button>

              </div>
            </div>
          );
        })}

      </div>

      {/* Recent Reports */}

      <div className="bg-[#111111] border border-zinc-800 rounded-2xl overflow-hidden">

        <div className="p-6 border-b border-zinc-800">
          <h2 className="text-2xl font-semibold text-white">
            Recent Reports
          </h2>
        </div>

        <table className="w-full">

          <thead className="bg-[#1b1b1b]">

            <tr>
              <th className="text-left px-6 py-4 text-gray-300">
                Report Name
              </th>

              <th className="text-left px-6 py-4 text-gray-300">
                Generated By
              </th>

              <th className="text-left px-6 py-4 text-gray-300">
                Date
              </th>

              <th className="text-left px-6 py-4 text-gray-300">
                Status
              </th>

              <th className="text-left px-6 py-4 text-gray-300">
                Action
              </th>
            </tr>

          </thead>

          <tbody>

            {[
              {
                name: "Attendance Report",
                by: "Admin",
                date: "28 Jul 2026",
                status: "Completed",
              },
              {
                name: "Payroll Report",
                by: "HR Manager",
                date: "27 Jul 2026",
                status: "Completed",
              },
              {
                name: "Performance Report",
                by: "Admin",
                date: "25 Jul 2026",
                status: "Completed",
              },
              {
                name: "Employee Report",
                by: "HR Executive",
                date: "24 Jul 2026",
                status: "Completed",
              },
            ].map((item) => (
              <tr
                key={item.name}
                className="border-t border-zinc-800 hover:bg-zinc-900"
              >
                <td className="px-6 py-4 text-white flex items-center gap-2">
                  <FileText size={18} className="text-yellow-400" />
                  {item.name}
                </td>

                <td className="px-6 py-4 text-gray-300">
                  {item.by}
                </td>

                <td className="px-6 py-4 text-gray-300">
                  {item.date}
                </td>

                <td className="px-6 py-4">
                  <span className="px-3 py-1 rounded-full bg-green-500/20 text-green-400 text-sm">
                    {item.status}
                  </span>
                </td>

                <td className="px-6 py-4">
                  <button className="bg-yellow-500 hover:bg-yellow-400 text-black px-3 py-2 rounded-lg">
                    Download
                  </button>
                </td>
              </tr>
            ))}

          </tbody>

        </table>

      </div>

    </div>
  );
}