"use client";

import Image from "next/image";
import Link from "next/link";
import { ArrowLeft } from "lucide-react";

export default function BarcodeDetailsPage() {
  return (
    <main className="min-h-screen bg-background-primary text-text-primary p-8">

      {/* Header */}

      <div className="flex justify-between items-center mb-10">

        <div>

          <h1 className="text-4xl font-bold text-accent-gold">
            Barcode Details
          </h1>

          <p className="text-text-secondary mt-2">
            View barcode information
          </p>

        </div>

        <Link
          href="/products/barcode"
          className="flex items-center gap-2 border border-yellow-500 text-accent-gold px-5 py-3 rounded-xl hover:bg-accent-gold hover:text-black transition"
        >
          <ArrowLeft size={18} />
          Back
        </Link>

      </div>

      {/* Card */}

      <div className="bg-background-secondary border border-border-theme rounded-2xl p-8 grid lg:grid-cols-2 gap-10">

        {/* Barcode Image */}

        <div className="bg-white rounded-xl flex justify-center items-center p-8">

          <Image
            src="/barcode/barcode1.png"
            alt="Barcode"
            width={500}
            height={200}
            className="object-contain"
          />

        </div>

        {/* Details */}

        <div className="space-y-5">

          <h2 className="text-3xl font-bold text-accent-gold">
            Gold Ring
          </h2>

          <p>
            <span className="text-text-secondary">
              SKU :
            </span>{" "}
            GLD001
          </p>

          <p>
            <span className="text-text-secondary">
              Barcode Value :
            </span>{" "}
            123456789012
          </p>

          <p>
            <span className="text-text-secondary">
              Barcode Type :
            </span>{" "}
            Code128
          </p>

          <p>
            <span className="text-text-secondary">
              Generated By :
            </span>{" "}
            Admin
          </p>

          <p>
            <span className="text-text-secondary">
              Created On :
            </span>{" "}
            24 July 2026
          </p>

          <div>

            <h3 className="text-xl font-semibold text-accent-gold mb-3">
              Description
            </h3>

            <p className="text-text-secondary leading-8">
              This barcode is used for billing, inventory tracking,
              product management, and warehouse scanning within the
              Luxury Gold ERP system.
            </p>

          </div>

          <button
            className="mt-6 bg-accent-gold hover:bg-accent-gold-hover text-black font-semibold px-8 py-3 rounded-xl transition"
          >
            Download Barcode
          </button>

        </div>

      </div>

    </main>
  );
}